### ISSUE TITLE
issue with all example codes

### ISSUE THREAD

**Issue by DDpal** [DIYables/DIYables_TFT_Touch_Shield#1]
Uh hi, my name is Daniel, i was trying to get any of your codes to work on my arduino uno r3 with your 3.5 tft lcd touch screen, but no matter what code i use an error pops up that says the following
In file included from C:\Users\danie\OneDrive\Documents\Arduino\libraries\DIYables_TFT_Touch_Shield\src/DIYables_TFT_Touch_Shield.h:5:0,
                 from C:\Users\danie\AppData\Local\Temp\.arduinoIDE-unsaved202571-11528-k1m998.3lbvg\sketch_aug1a\sketch_aug1a.ino:1:
C:\Users\danie\OneDrive\Documents\Arduino\libraries\Adafruit_GFX_Library/Adafruit_GFX.h:12:10: fatal error: Adafruit_I2CDevice.h: No such file or directory
 #include <Adafruit_I2CDevice.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1
and i dont know why, or how i can fix it since i tried adding that library already and it didnt work

**Comment by DIYables** [comment]
Hello,
 The error showed that the depency library Adafruit_I2CDevice.h is not installed in your PC, or it is accidently deleted.

Please install that library.

Another way: uninstall Adafruit_GFX and reinstall it. It will automatically include the dependency libraries.

**Comment by DDpal** [comment]
hi i did that and still have an error message
In file included from C:\Users\danie\OneDrive\Documents\Arduino\sketch_calc\sketch_calc.ino:1:0:
C:\Users\danie\OneDrive\Documents\Arduino\libraries\Adafruit_GFX_Library/Adafruit_GFX.h:12:10: fatal error: Adafruit_I2CDevice.h: No such file or directory
 #include <Adafruit_I2CDevice.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

**Comment by DDpal** [comment]
and yes i also did the include of the adafruit_IC2Device

**Comment by DIYables** [comment]
Sometime, Arduino IDE has error when installing the library. 

Firsly, make sure that the "**Adafruit_BusIO**" was installed. This library contain Adafruit_I2CDevice.h file.

<img width="838" height="235" alt="Image" src="https://github.com/user-attachments/assets/35118238-6ab8-47ff-b7f8-ac699ea55fb2" />

If it still does not work. If possible, please try to test on another PC. If not, please manually  delete all Adafruit_xxxxx library on your library installed, (usually in C:\Users\YOUR_USER_NAME\Documents\Arduino\libraries ), also delete our library. Then reinstall the our library.

Best regards,
DIYables,

**Comment by DDpal** [comment]
i just put that in the libraries, but now it says this:
In file included from C:\Users\danie\OneDrive\Documents\Arduino\sketch_calc\sketch_calc.ino:7:0:
C:\Users\danie\OneDrive\Documents\Arduino\libraries\DIYables_TFT_Touch_Shield\src/DIYables_TFT_Touch_Shield.h:6:10: fatal error: DIYables_TFT_Shield.h: No such file or directory
 #include <DIYables_TFT_Shield.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1
even though that library is in the files and is included too

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/f2dee4b5-f43d-48b9-9f63-19d7427731ed" />
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/40eb9c1c-3329-44d9-a1fb-8007843251cf" />

**Comment by DIYables** [comment]
Thank you for your screenshot.

It shows the source of issues:

- You have not installed the library dependency "DIYables_TFT_Shield"
- You used incorrect code.

Please follow the below tutorials, which include the instruction on how to install library and dependency, and the example code:
[Arduino - TFT LCD Touch Screen Display](https://arduinogetstarted.com/tutorials/arduino-tft-lcd-touch-screen-display)
[Arduino UNO R4 - TFT LCD Touch Screen Display](https://newbiely.com/tutorials/arduino-uno-r4/arduino-uno-r4-tft-lcd-touch-screen-display)
These tutorials are also mentioned on the product page and the readme.md of this library

Please run our example code to test if it works.

We will not support your modified code. Instead, you can make questions for your modified code on Arduino Forum. 

Have a great day!
Best regards,
